name: hello
on:
  push:
    branches: [ main ]

jobs:
  Greet:
    runs-on: ubuntu-22.04

    steps:
      - name: say hello to users
        run: echo "hello dosto"

      - name: say hello to user name
        run: echo "Hello my friend $USER"
      
