name: Build Push and Deploy to kubernetes

on:
    push:
        branches:
            - main

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - name: checkout source code
              uses: actions/checkout@v4

            - name: log in to Docker Hub
              run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USER }}" --password-stdin
              
            - name: Build Docker Image
              run: docker build -t ${{ secrets.DOCKERHUB_USER }}/myapp:v4 .
              
            - name: Push Docker Image
              run: docker push ${{ secrets.DOCKERHUB_USER }}/myapp:v4


            - name: Deploy to kubernetes on EC2 via SSH
              uses: appleboy/ssh-action@v1.0.3
              with:
                host: ${{ secrets.EC2_HOST }}
                username: ${{ secrets.EC2_USER }}
                key: ${{ secrets.EC2_SSH_KEY }}
                script: |
                  kubectl get nodes
                  docker pull ${{ secrets.DOCKERHUB_USER }}/myapp:v4
                  ubectl set image deployment/myapp-deployment myapp=${{ secrets.DOCKERHUB_USER }}/myapp:v4
                  kubectl rollout status deployment/myapp-deployment --timeout=120s
                  kubectl get pods -o wide


            # Setup the kubeconfig and will change it

            # - name: Set up kubeconfig
            #   run: |
            #      mkdir -p $HOME/.kube
            #      cat <<'EOF' > $HOME/.kube/config
            #      ${{ secrets.KUBE_CONFIG }}
            #      EOF
            #      chmod 600 $HOME/.kube/config


            #   #run: |
            #     #mkdir -p $HOME/.kube
            #     #echo "${{ secrets.KUBE_CONFIG }}" | base64 -d > $HOME/.kube/config
            #     #chmod 600 $HOME/.kube/config

            # - name: verify cluster access
            #   run: kubectl get nodes

            # - name: Update the kubernetes deployement image
            #   run: kubectl set image deployment/myapp-deployment myapp=${{ secrets.DOCKERHUB_USER }}/myapp:v4

            # - name: check rollout status
            #   run: kubectl rollout status deployment/myapp-deployment --timeout=120s